services:
  mysql:
    image: mysql:8.0
    container_name: db-mysql
    networks:
      - db-project
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql

  web:
    build: ./web
    container_name: db-web
    networks:
      - db-project
      - web
    depends_on:
      - mysql
    labels:
      treafik.enable: true
      traefik.http.routers.dbproject.rule: Host(`dbproject.whipaper.me`)
      traefik.http.routers.dbproject.entrypoints: websecure
      traefik.http.services.dbproject.loadbalancer.server.port: 80

networks:
  db-project:
  web:
    external: true
