name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger webhook
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}

      - name: Create GitHub Deployment
        uses: peter-evans/create-deployment@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          transient-environment: false