name: MWB Changes → Convert to SQL

on:
  push:
    paths:
      - "db/schema.mwb"

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - run: sudo apt-get install -y composer

      - run: composer require --dev mysql-workbench-schema-exporter/mysql-workbench-schema-exporter

      - run: vendor/bin/mysql-workbench-schema-export --export=sql db/schema.mwb db/schema.sql

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add db/schema.sql
          git commit -m "Auto-converted schema.mwb → schema.sql" || echo "No changes"
          git push
